// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: textsearch.proto

package com.google.search.app;

public final class Textsearch {
  private Textsearch() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.search.app.SearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string search_id = 1;</code>
     */
    boolean hasSearchId();
    /**
     * <code>required string search_id = 1;</code>
     */
    java.lang.String getSearchId();
    /**
     * <code>required string search_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSearchIdBytes();

    /**
     * <code>optional uint32 msg_type = 4;</code>
     */
    boolean hasMsgType();
    /**
     * <code>optional uint32 msg_type = 4;</code>
     */
    int getMsgType();

    /**
     * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
     */
    boolean hasSug();
    /**
     * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
     */
    com.google.search.app.Textsearch.SearchResultPart getSug();
    /**
     * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
     */
    com.google.search.app.Textsearch.SearchResultPartOrBuilder getSugOrBuilder();

    /**
     * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
     */
    boolean hasResult();
    /**
     * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
     */
    com.google.search.app.Textsearch.SearchResultPart getResult();
    /**
     * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
     */
    com.google.search.app.Textsearch.SearchResultPartOrBuilder getResultOrBuilder();

    /**
     * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
     */
    boolean hasSR102();
    /**
     * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
     */
    com.google.search.app.Textsearch.Empty getSR102();
    /**
     * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
     */
    com.google.search.app.Textsearch.EmptyOrBuilder getSR102OrBuilder();
  }
  /**
   * Protobuf type {@code com.google.search.app.SearchResponse}
   */
  public static final class SearchResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.google.search.app.SearchResponse)
      SearchResponseOrBuilder {
    // Use SearchResponse.newBuilder() to construct.
    private SearchResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SearchResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SearchResponse defaultInstance;
    public static SearchResponse getDefaultInstance() {
      return defaultInstance;
    }

    public SearchResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              searchId_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              msgType_ = input.readUInt32();
              break;
            }
            case 802: {
              com.google.search.app.Textsearch.SearchResultPart.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = sug_.toBuilder();
              }
              sug_ = input.readMessage(com.google.search.app.Textsearch.SearchResultPart.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sug_);
                sug_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 810: {
              com.google.search.app.Textsearch.SearchResultPart.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(com.google.search.app.Textsearch.SearchResultPart.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 818: {
              com.google.search.app.Textsearch.Empty.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = sR102_.toBuilder();
              }
              sR102_ = input.readMessage(com.google.search.app.Textsearch.Empty.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sR102_);
                sR102_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.search.app.Textsearch.internal_static_com_google_search_app_SearchResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.search.app.Textsearch.internal_static_com_google_search_app_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.search.app.Textsearch.SearchResponse.class, com.google.search.app.Textsearch.SearchResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<SearchResponse> PARSER =
        new com.google.protobuf.AbstractParser<SearchResponse>() {
      public SearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SEARCH_ID_FIELD_NUMBER = 1;
    private java.lang.Object searchId_;
    /**
     * <code>required string search_id = 1;</code>
     */
    public boolean hasSearchId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string search_id = 1;</code>
     */
    public java.lang.String getSearchId() {
      java.lang.Object ref = searchId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          searchId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string search_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSearchIdBytes() {
      java.lang.Object ref = searchId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 4;
    private int msgType_;
    /**
     * <code>optional uint32 msg_type = 4;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 msg_type = 4;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int SUG_FIELD_NUMBER = 100;
    private com.google.search.app.Textsearch.SearchResultPart sug_;
    /**
     * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
     */
    public boolean hasSug() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
     */
    public com.google.search.app.Textsearch.SearchResultPart getSug() {
      return sug_;
    }
    /**
     * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
     */
    public com.google.search.app.Textsearch.SearchResultPartOrBuilder getSugOrBuilder() {
      return sug_;
    }

    public static final int RESULT_FIELD_NUMBER = 101;
    private com.google.search.app.Textsearch.SearchResultPart result_;
    /**
     * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
     */
    public com.google.search.app.Textsearch.SearchResultPart getResult() {
      return result_;
    }
    /**
     * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
     */
    public com.google.search.app.Textsearch.SearchResultPartOrBuilder getResultOrBuilder() {
      return result_;
    }

    public static final int SR102_FIELD_NUMBER = 102;
    private com.google.search.app.Textsearch.Empty sR102_;
    /**
     * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
     */
    public boolean hasSR102() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
     */
    public com.google.search.app.Textsearch.Empty getSR102() {
      return sR102_;
    }
    /**
     * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
     */
    public com.google.search.app.Textsearch.EmptyOrBuilder getSR102OrBuilder() {
      return sR102_;
    }

    private void initFields() {
      searchId_ = "";
      msgType_ = 0;
      sug_ = com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance();
      result_ = com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance();
      sR102_ = com.google.search.app.Textsearch.Empty.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSearchId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSearchIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(4, msgType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(100, sug_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(101, result_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(102, sR102_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSearchIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, msgType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(100, sug_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, result_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, sR102_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.search.app.Textsearch.SearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.search.app.Textsearch.SearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.SearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.search.app.Textsearch.SearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.SearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.search.app.Textsearch.SearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.SearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.search.app.Textsearch.SearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.search.app.Textsearch.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.search.app.Textsearch.SearchResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.search.app.SearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.search.app.SearchResponse)
        com.google.search.app.Textsearch.SearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.search.app.Textsearch.internal_static_com_google_search_app_SearchResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.search.app.Textsearch.internal_static_com_google_search_app_SearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.search.app.Textsearch.SearchResponse.class, com.google.search.app.Textsearch.SearchResponse.Builder.class);
      }

      // Construct using com.google.search.app.Textsearch.SearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSugFieldBuilder();
          getResultFieldBuilder();
          getSR102FieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        searchId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (sugBuilder_ == null) {
          sug_ = com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance();
        } else {
          sugBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (resultBuilder_ == null) {
          result_ = com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (sR102Builder_ == null) {
          sR102_ = com.google.search.app.Textsearch.Empty.getDefaultInstance();
        } else {
          sR102Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.search.app.Textsearch.internal_static_com_google_search_app_SearchResponse_descriptor;
      }

      public com.google.search.app.Textsearch.SearchResponse getDefaultInstanceForType() {
        return com.google.search.app.Textsearch.SearchResponse.getDefaultInstance();
      }

      public com.google.search.app.Textsearch.SearchResponse build() {
        com.google.search.app.Textsearch.SearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.search.app.Textsearch.SearchResponse buildPartial() {
        com.google.search.app.Textsearch.SearchResponse result = new com.google.search.app.Textsearch.SearchResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.searchId_ = searchId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (sugBuilder_ == null) {
          result.sug_ = sug_;
        } else {
          result.sug_ = sugBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (sR102Builder_ == null) {
          result.sR102_ = sR102_;
        } else {
          result.sR102_ = sR102Builder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.search.app.Textsearch.SearchResponse) {
          return mergeFrom((com.google.search.app.Textsearch.SearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.search.app.Textsearch.SearchResponse other) {
        if (other == com.google.search.app.Textsearch.SearchResponse.getDefaultInstance()) return this;
        if (other.hasSearchId()) {
          bitField0_ |= 0x00000001;
          searchId_ = other.searchId_;
          onChanged();
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasSug()) {
          mergeSug(other.getSug());
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        if (other.hasSR102()) {
          mergeSR102(other.getSR102());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSearchId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.search.app.Textsearch.SearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.search.app.Textsearch.SearchResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object searchId_ = "";
      /**
       * <code>required string search_id = 1;</code>
       */
      public boolean hasSearchId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string search_id = 1;</code>
       */
      public java.lang.String getSearchId() {
        java.lang.Object ref = searchId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            searchId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string search_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSearchIdBytes() {
        java.lang.Object ref = searchId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          searchId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string search_id = 1;</code>
       */
      public Builder setSearchId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        searchId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string search_id = 1;</code>
       */
      public Builder clearSearchId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        searchId_ = getDefaultInstance().getSearchId();
        onChanged();
        return this;
      }
      /**
       * <code>required string search_id = 1;</code>
       */
      public Builder setSearchIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        searchId_ = value;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>optional uint32 msg_type = 4;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 msg_type = 4;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>optional uint32 msg_type = 4;</code>
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000002;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 msg_type = 4;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.search.app.Textsearch.SearchResultPart sug_ = com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.search.app.Textsearch.SearchResultPart, com.google.search.app.Textsearch.SearchResultPart.Builder, com.google.search.app.Textsearch.SearchResultPartOrBuilder> sugBuilder_;
      /**
       * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
       */
      public boolean hasSug() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
       */
      public com.google.search.app.Textsearch.SearchResultPart getSug() {
        if (sugBuilder_ == null) {
          return sug_;
        } else {
          return sugBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
       */
      public Builder setSug(com.google.search.app.Textsearch.SearchResultPart value) {
        if (sugBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sug_ = value;
          onChanged();
        } else {
          sugBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
       */
      public Builder setSug(
          com.google.search.app.Textsearch.SearchResultPart.Builder builderForValue) {
        if (sugBuilder_ == null) {
          sug_ = builderForValue.build();
          onChanged();
        } else {
          sugBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
       */
      public Builder mergeSug(com.google.search.app.Textsearch.SearchResultPart value) {
        if (sugBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              sug_ != com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance()) {
            sug_ =
              com.google.search.app.Textsearch.SearchResultPart.newBuilder(sug_).mergeFrom(value).buildPartial();
          } else {
            sug_ = value;
          }
          onChanged();
        } else {
          sugBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
       */
      public Builder clearSug() {
        if (sugBuilder_ == null) {
          sug_ = com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance();
          onChanged();
        } else {
          sugBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
       */
      public com.google.search.app.Textsearch.SearchResultPart.Builder getSugBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSugFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
       */
      public com.google.search.app.Textsearch.SearchResultPartOrBuilder getSugOrBuilder() {
        if (sugBuilder_ != null) {
          return sugBuilder_.getMessageOrBuilder();
        } else {
          return sug_;
        }
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart sug = 100;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.search.app.Textsearch.SearchResultPart, com.google.search.app.Textsearch.SearchResultPart.Builder, com.google.search.app.Textsearch.SearchResultPartOrBuilder> 
          getSugFieldBuilder() {
        if (sugBuilder_ == null) {
          sugBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.search.app.Textsearch.SearchResultPart, com.google.search.app.Textsearch.SearchResultPart.Builder, com.google.search.app.Textsearch.SearchResultPartOrBuilder>(
                  getSug(),
                  getParentForChildren(),
                  isClean());
          sug_ = null;
        }
        return sugBuilder_;
      }

      private com.google.search.app.Textsearch.SearchResultPart result_ = com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.search.app.Textsearch.SearchResultPart, com.google.search.app.Textsearch.SearchResultPart.Builder, com.google.search.app.Textsearch.SearchResultPartOrBuilder> resultBuilder_;
      /**
       * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
       */
      public com.google.search.app.Textsearch.SearchResultPart getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
       */
      public Builder setResult(com.google.search.app.Textsearch.SearchResultPart value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
       */
      public Builder setResult(
          com.google.search.app.Textsearch.SearchResultPart.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
       */
      public Builder mergeResult(com.google.search.app.Textsearch.SearchResultPart value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              result_ != com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance()) {
            result_ =
              com.google.search.app.Textsearch.SearchResultPart.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
       */
      public com.google.search.app.Textsearch.SearchResultPart.Builder getResultBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
       */
      public com.google.search.app.Textsearch.SearchResultPartOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>optional .com.google.search.app.SearchResultPart result = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.search.app.Textsearch.SearchResultPart, com.google.search.app.Textsearch.SearchResultPart.Builder, com.google.search.app.Textsearch.SearchResultPartOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.search.app.Textsearch.SearchResultPart, com.google.search.app.Textsearch.SearchResultPart.Builder, com.google.search.app.Textsearch.SearchResultPartOrBuilder>(
                  getResult(),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      private com.google.search.app.Textsearch.Empty sR102_ = com.google.search.app.Textsearch.Empty.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.search.app.Textsearch.Empty, com.google.search.app.Textsearch.Empty.Builder, com.google.search.app.Textsearch.EmptyOrBuilder> sR102Builder_;
      /**
       * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
       */
      public boolean hasSR102() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
       */
      public com.google.search.app.Textsearch.Empty getSR102() {
        if (sR102Builder_ == null) {
          return sR102_;
        } else {
          return sR102Builder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
       */
      public Builder setSR102(com.google.search.app.Textsearch.Empty value) {
        if (sR102Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sR102_ = value;
          onChanged();
        } else {
          sR102Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
       */
      public Builder setSR102(
          com.google.search.app.Textsearch.Empty.Builder builderForValue) {
        if (sR102Builder_ == null) {
          sR102_ = builderForValue.build();
          onChanged();
        } else {
          sR102Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
       */
      public Builder mergeSR102(com.google.search.app.Textsearch.Empty value) {
        if (sR102Builder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              sR102_ != com.google.search.app.Textsearch.Empty.getDefaultInstance()) {
            sR102_ =
              com.google.search.app.Textsearch.Empty.newBuilder(sR102_).mergeFrom(value).buildPartial();
          } else {
            sR102_ = value;
          }
          onChanged();
        } else {
          sR102Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
       */
      public Builder clearSR102() {
        if (sR102Builder_ == null) {
          sR102_ = com.google.search.app.Textsearch.Empty.getDefaultInstance();
          onChanged();
        } else {
          sR102Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
       */
      public com.google.search.app.Textsearch.Empty.Builder getSR102Builder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getSR102FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
       */
      public com.google.search.app.Textsearch.EmptyOrBuilder getSR102OrBuilder() {
        if (sR102Builder_ != null) {
          return sR102Builder_.getMessageOrBuilder();
        } else {
          return sR102_;
        }
      }
      /**
       * <code>optional .com.google.search.app.Empty SR102 = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.search.app.Textsearch.Empty, com.google.search.app.Textsearch.Empty.Builder, com.google.search.app.Textsearch.EmptyOrBuilder> 
          getSR102FieldBuilder() {
        if (sR102Builder_ == null) {
          sR102Builder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.search.app.Textsearch.Empty, com.google.search.app.Textsearch.Empty.Builder, com.google.search.app.Textsearch.EmptyOrBuilder>(
                  getSR102(),
                  getParentForChildren(),
                  isClean());
          sR102_ = null;
        }
        return sR102Builder_;
      }

      // @@protoc_insertion_point(builder_scope:com.google.search.app.SearchResponse)
    }

    static {
      defaultInstance = new SearchResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.search.app.SearchResponse)
  }

  public interface SearchResultPartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.search.app.SearchResultPart)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 fin_stream = 1;</code>
     */
    boolean hasFinStream();
    /**
     * <code>optional uint32 fin_stream = 1;</code>
     */
    int getFinStream();

    /**
     * <code>optional string text_data = 2;</code>
     */
    boolean hasTextData();
    /**
     * <code>optional string text_data = 2;</code>
     */
    java.lang.String getTextData();
    /**
     * <code>optional string text_data = 2;</code>
     */
    com.google.protobuf.ByteString
        getTextDataBytes();

    /**
     * <code>optional string html_data = 7;</code>
     */
    boolean hasHtmlData();
    /**
     * <code>optional string html_data = 7;</code>
     */
    java.lang.String getHtmlData();
    /**
     * <code>optional string html_data = 7;</code>
     */
    com.google.protobuf.ByteString
        getHtmlDataBytes();

    /**
     * <code>optional string encoding = 8;</code>
     */
    boolean hasEncoding();
    /**
     * <code>optional string encoding = 8;</code>
     */
    java.lang.String getEncoding();
    /**
     * <code>optional string encoding = 8;</code>
     */
    com.google.protobuf.ByteString
        getEncodingBytes();
  }
  /**
   * Protobuf type {@code com.google.search.app.SearchResultPart}
   */
  public static final class SearchResultPart extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.google.search.app.SearchResultPart)
      SearchResultPartOrBuilder {
    // Use SearchResultPart.newBuilder() to construct.
    private SearchResultPart(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SearchResultPart(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SearchResultPart defaultInstance;
    public static SearchResultPart getDefaultInstance() {
      return defaultInstance;
    }

    public SearchResultPart getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SearchResultPart(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              finStream_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              textData_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              htmlData_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              encoding_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.search.app.Textsearch.internal_static_com_google_search_app_SearchResultPart_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.search.app.Textsearch.internal_static_com_google_search_app_SearchResultPart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.search.app.Textsearch.SearchResultPart.class, com.google.search.app.Textsearch.SearchResultPart.Builder.class);
    }

    public static com.google.protobuf.Parser<SearchResultPart> PARSER =
        new com.google.protobuf.AbstractParser<SearchResultPart>() {
      public SearchResultPart parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchResultPart(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResultPart> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FIN_STREAM_FIELD_NUMBER = 1;
    private int finStream_;
    /**
     * <code>optional uint32 fin_stream = 1;</code>
     */
    public boolean hasFinStream() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 fin_stream = 1;</code>
     */
    public int getFinStream() {
      return finStream_;
    }

    public static final int TEXT_DATA_FIELD_NUMBER = 2;
    private java.lang.Object textData_;
    /**
     * <code>optional string text_data = 2;</code>
     */
    public boolean hasTextData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string text_data = 2;</code>
     */
    public java.lang.String getTextData() {
      java.lang.Object ref = textData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          textData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text_data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextDataBytes() {
      java.lang.Object ref = textData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HTML_DATA_FIELD_NUMBER = 7;
    private java.lang.Object htmlData_;
    /**
     * <code>optional string html_data = 7;</code>
     */
    public boolean hasHtmlData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string html_data = 7;</code>
     */
    public java.lang.String getHtmlData() {
      java.lang.Object ref = htmlData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          htmlData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string html_data = 7;</code>
     */
    public com.google.protobuf.ByteString
        getHtmlDataBytes() {
      java.lang.Object ref = htmlData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        htmlData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCODING_FIELD_NUMBER = 8;
    private java.lang.Object encoding_;
    /**
     * <code>optional string encoding = 8;</code>
     */
    public boolean hasEncoding() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string encoding = 8;</code>
     */
    public java.lang.String getEncoding() {
      java.lang.Object ref = encoding_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encoding_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string encoding = 8;</code>
     */
    public com.google.protobuf.ByteString
        getEncodingBytes() {
      java.lang.Object ref = encoding_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      finStream_ = 0;
      textData_ = "";
      htmlData_ = "";
      encoding_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, finStream_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTextDataBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(7, getHtmlDataBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(8, getEncodingBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, finStream_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTextDataBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getHtmlDataBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getEncodingBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.search.app.Textsearch.SearchResultPart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.search.app.Textsearch.SearchResultPart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.SearchResultPart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.search.app.Textsearch.SearchResultPart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.SearchResultPart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.search.app.Textsearch.SearchResultPart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.SearchResultPart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.search.app.Textsearch.SearchResultPart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.SearchResultPart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.search.app.Textsearch.SearchResultPart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.search.app.Textsearch.SearchResultPart prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.search.app.SearchResultPart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.search.app.SearchResultPart)
        com.google.search.app.Textsearch.SearchResultPartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.search.app.Textsearch.internal_static_com_google_search_app_SearchResultPart_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.search.app.Textsearch.internal_static_com_google_search_app_SearchResultPart_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.search.app.Textsearch.SearchResultPart.class, com.google.search.app.Textsearch.SearchResultPart.Builder.class);
      }

      // Construct using com.google.search.app.Textsearch.SearchResultPart.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        finStream_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        textData_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        htmlData_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        encoding_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.search.app.Textsearch.internal_static_com_google_search_app_SearchResultPart_descriptor;
      }

      public com.google.search.app.Textsearch.SearchResultPart getDefaultInstanceForType() {
        return com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance();
      }

      public com.google.search.app.Textsearch.SearchResultPart build() {
        com.google.search.app.Textsearch.SearchResultPart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.search.app.Textsearch.SearchResultPart buildPartial() {
        com.google.search.app.Textsearch.SearchResultPart result = new com.google.search.app.Textsearch.SearchResultPart(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.finStream_ = finStream_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.textData_ = textData_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.htmlData_ = htmlData_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.encoding_ = encoding_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.search.app.Textsearch.SearchResultPart) {
          return mergeFrom((com.google.search.app.Textsearch.SearchResultPart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.search.app.Textsearch.SearchResultPart other) {
        if (other == com.google.search.app.Textsearch.SearchResultPart.getDefaultInstance()) return this;
        if (other.hasFinStream()) {
          setFinStream(other.getFinStream());
        }
        if (other.hasTextData()) {
          bitField0_ |= 0x00000002;
          textData_ = other.textData_;
          onChanged();
        }
        if (other.hasHtmlData()) {
          bitField0_ |= 0x00000004;
          htmlData_ = other.htmlData_;
          onChanged();
        }
        if (other.hasEncoding()) {
          bitField0_ |= 0x00000008;
          encoding_ = other.encoding_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.search.app.Textsearch.SearchResultPart parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.search.app.Textsearch.SearchResultPart) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int finStream_ ;
      /**
       * <code>optional uint32 fin_stream = 1;</code>
       */
      public boolean hasFinStream() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 fin_stream = 1;</code>
       */
      public int getFinStream() {
        return finStream_;
      }
      /**
       * <code>optional uint32 fin_stream = 1;</code>
       */
      public Builder setFinStream(int value) {
        bitField0_ |= 0x00000001;
        finStream_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 fin_stream = 1;</code>
       */
      public Builder clearFinStream() {
        bitField0_ = (bitField0_ & ~0x00000001);
        finStream_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object textData_ = "";
      /**
       * <code>optional string text_data = 2;</code>
       */
      public boolean hasTextData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string text_data = 2;</code>
       */
      public java.lang.String getTextData() {
        java.lang.Object ref = textData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            textData_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text_data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextDataBytes() {
        java.lang.Object ref = textData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          textData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text_data = 2;</code>
       */
      public Builder setTextData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        textData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text_data = 2;</code>
       */
      public Builder clearTextData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        textData_ = getDefaultInstance().getTextData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text_data = 2;</code>
       */
      public Builder setTextDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        textData_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object htmlData_ = "";
      /**
       * <code>optional string html_data = 7;</code>
       */
      public boolean hasHtmlData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string html_data = 7;</code>
       */
      public java.lang.String getHtmlData() {
        java.lang.Object ref = htmlData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            htmlData_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string html_data = 7;</code>
       */
      public com.google.protobuf.ByteString
          getHtmlDataBytes() {
        java.lang.Object ref = htmlData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          htmlData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string html_data = 7;</code>
       */
      public Builder setHtmlData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        htmlData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string html_data = 7;</code>
       */
      public Builder clearHtmlData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        htmlData_ = getDefaultInstance().getHtmlData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string html_data = 7;</code>
       */
      public Builder setHtmlDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        htmlData_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object encoding_ = "";
      /**
       * <code>optional string encoding = 8;</code>
       */
      public boolean hasEncoding() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string encoding = 8;</code>
       */
      public java.lang.String getEncoding() {
        java.lang.Object ref = encoding_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            encoding_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string encoding = 8;</code>
       */
      public com.google.protobuf.ByteString
          getEncodingBytes() {
        java.lang.Object ref = encoding_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          encoding_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string encoding = 8;</code>
       */
      public Builder setEncoding(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        encoding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string encoding = 8;</code>
       */
      public Builder clearEncoding() {
        bitField0_ = (bitField0_ & ~0x00000008);
        encoding_ = getDefaultInstance().getEncoding();
        onChanged();
        return this;
      }
      /**
       * <code>optional string encoding = 8;</code>
       */
      public Builder setEncodingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        encoding_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.search.app.SearchResultPart)
    }

    static {
      defaultInstance = new SearchResultPart(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.search.app.SearchResultPart)
  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.search.app.Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.google.search.app.Empty}
   */
  public static final class Empty extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.google.search.app.Empty)
      EmptyOrBuilder {
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Empty(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Empty defaultInstance;
    public static Empty getDefaultInstance() {
      return defaultInstance;
    }

    public Empty getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.search.app.Textsearch.internal_static_com_google_search_app_Empty_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.search.app.Textsearch.internal_static_com_google_search_app_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.search.app.Textsearch.Empty.class, com.google.search.app.Textsearch.Empty.Builder.class);
    }

    public static com.google.protobuf.Parser<Empty> PARSER =
        new com.google.protobuf.AbstractParser<Empty>() {
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.search.app.Textsearch.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.search.app.Textsearch.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.search.app.Textsearch.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.search.app.Textsearch.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.search.app.Textsearch.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.search.app.Textsearch.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.search.app.Textsearch.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.search.app.Textsearch.Empty prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.search.app.Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.search.app.Empty)
        com.google.search.app.Textsearch.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.search.app.Textsearch.internal_static_com_google_search_app_Empty_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.search.app.Textsearch.internal_static_com_google_search_app_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.search.app.Textsearch.Empty.class, com.google.search.app.Textsearch.Empty.Builder.class);
      }

      // Construct using com.google.search.app.Textsearch.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.search.app.Textsearch.internal_static_com_google_search_app_Empty_descriptor;
      }

      public com.google.search.app.Textsearch.Empty getDefaultInstanceForType() {
        return com.google.search.app.Textsearch.Empty.getDefaultInstance();
      }

      public com.google.search.app.Textsearch.Empty build() {
        com.google.search.app.Textsearch.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.search.app.Textsearch.Empty buildPartial() {
        com.google.search.app.Textsearch.Empty result = new com.google.search.app.Textsearch.Empty(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.search.app.Textsearch.Empty) {
          return mergeFrom((com.google.search.app.Textsearch.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.search.app.Textsearch.Empty other) {
        if (other == com.google.search.app.Textsearch.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.search.app.Textsearch.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.search.app.Textsearch.Empty) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.search.app.Empty)
    }

    static {
      defaultInstance = new Empty(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.search.app.Empty)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_search_app_SearchResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_search_app_SearchResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_search_app_SearchResultPart_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_search_app_SearchResultPart_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_search_app_Empty_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_search_app_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020textsearch.proto\022\025com.google.search.ap" +
      "p\"\321\001\n\016SearchResponse\022\021\n\tsearch_id\030\001 \002(\t\022" +
      "\020\n\010msg_type\030\004 \001(\r\0224\n\003sug\030d \001(\0132\'.com.goo" +
      "gle.search.app.SearchResultPart\0227\n\006resul" +
      "t\030e \001(\0132\'.com.google.search.app.SearchRe" +
      "sultPart\022+\n\005SR102\030f \001(\0132\034.com.google.sea" +
      "rch.app.Empty\"^\n\020SearchResultPart\022\022\n\nfin" +
      "_stream\030\001 \001(\r\022\021\n\ttext_data\030\002 \001(\t\022\021\n\thtml" +
      "_data\030\007 \001(\t\022\020\n\010encoding\030\010 \001(\t\"\007\n\005Empty"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_google_search_app_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_search_app_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_google_search_app_SearchResponse_descriptor,
        new java.lang.String[] { "SearchId", "MsgType", "Sug", "Result", "SR102", });
    internal_static_com_google_search_app_SearchResultPart_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_google_search_app_SearchResultPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_google_search_app_SearchResultPart_descriptor,
        new java.lang.String[] { "FinStream", "TextData", "HtmlData", "Encoding", });
    internal_static_com_google_search_app_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_google_search_app_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_google_search_app_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
